name: Qscpi000_basic_ranalysis0.1.0
channels:
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=3.4.3
  - bioconductor-scpipe=1.2.1
  - bioconductor-singlecellexperiment=1.0.0
  - bioconductor-summarizedexperiment=1.8.0
  - bioconductor-delayedarray=0.4.1
  - r-matrixstats=0.54.0
  - bioconductor-biobase=2.38.0
  - bioconductor-genomicranges=1.30.3
  - bioconductor-genomeinfodb=1.14.0
  - bioconductor-iranges=2.12.0
  - bioconductor-s4vectors=0.16.0
  - bioconductor-biocgenerics=0.24.0
  - r-plyr=1.8.4
  - r-rcolorbrewer=1.1_2
  - r-reshape2=1.4.3
  - r-ggplot2=3.0.0
