name: QMICE000_multiomics_ranalysis0.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.6.0
  - bioconductor-mofadata=1.0.0
  - bioconductor-multiassayexperiment=1.10.4
  - bioconductor-summarizedexperiment=1.14.0
  - bioconductor-delayedarray=0.10.0
  - bioconductor-biocparallel=1.18.0
  - r-matrixstats=0.54.0
  - bioconductor-biobase=2.44.0
  - bioconductor-genomicranges=1.36.0
  - bioconductor-genomeinfodb=1.20.0
  - bioconductor-iranges=2.18.1
  - bioconductor-s4vectors=0.22.0
  - bioconductor-biocgenerics=0.30.0
  - r-reticulate=1.12
  - bioconductor-mofa=1.0.0
  - bioconductor-biomart=2.40.3
