name: QTEST_ranalysis0.1.0
channels:
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=3.5.1
  - bioconductor-scpipe=1.4.1
  - bioconductor-singlecellexperiment=1.4.0
  - bioconductor-summarizedexperiment=1.12.0
  - bioconductor-delayedarray=0.8.0
  - bioconductor-biocparallel=1.16.6
  - r-matrixstats=0.54.0
  - bioconductor-biobase=2.42.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-genomeinfodb=1.18.1
  - bioconductor-iranges=2.16.0
  - bioconductor-s4vectors=0.20.1
  - bioconductor-biocgenerics=0.28.0
  - r-ggplot2=3.0.0
