name: QSCRN000_scpipe_ranalysis0.1.0
channels:
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=3.6.0
  - bioconductor-biomart
  - r-plyr=1.8.4
  - r-pheatmap=1.0.12
  - bioconductor-scpipe
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-delayedarray
  - bioconductor-biocparallel=1.18.0
  - r-matrixstats=0.54.0
  - bioconductor-biobase
  - bioconductor-genomicranges
  - bioconductor-genomeinfodb
  - bioconductor-iranges
  - bioconductor-s4vectors
  - bioconductor-biocgenerics
  - r-ggplot2
  - r-reshape2=1.4.3
  - bioconductor-sc3
  - bioconductor-biomart=2.38.0
  - bioconductor-scpipe=1.4.1
  - bioconductor-singlecellexperiment=1.4.0
  - bioconductor-summarizedexperiment=1.12.0
  - bioconductor-delayedarray=0.8.0
  - bioconductor-biobase=2.42.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-genomeinfodb=1.18.1
  - bioconductor-iranges=2.16.0
  - bioconductor-s4vectors=0.20.1
  - bioconductor-biocgenerics=0.28.0
  - r-ggplot2=3.0.0
  - bioconductor-sc3=1.10.0
